### ISSUE TITLE
Mastersthesis BibTeX entry type

### ISSUE THREAD

**Issue by Xennis** [arkuuu/publin#19]
In publin the BibTeX entry type `masterthesis` is implemented. But according to my knowledge only the type `mastersthesis` (master<strong>s</strong> and not master) exists (check: https://en.wikipedia.org/wiki/BibTeX#Entry_types or http://nwalsh.com/tex/texhelp/bibtx-16.html)

**Comment by arkuuu** [comment]
funny that i never noticed this! Thanks!

**Comment by Xennis** [comment]
Don't you have to change more lines of code, e.g. the `$supported_types` in modules/Bibtex.php (see https://github.com/arkuuu/publin/search?l=php&q=masterthesis&utf8=%E2%9C%93)

**Comment by arkuuu** [comment]
well, you're right. I fixed it.
