### ISSUE TITLE
how to activate indices

### ISSUE THREAD

**Issue by h1ps** [arkuuu/publin#23]
If i try to activate the indices like introduced in the config file, i get the following error

```
/*
 * This constant allows to show only a subset of the available indices
 * on the author page by providing the case-sensitive names of the
 * requested indices as shown in the example below. If all available
 * indices should be displayed, the constant should be null.
 *
 * Example:
 * const INDICES_SELECTION = '
 *     "h-index",
 *     "mf-index"
 * ';
 */
 const INDICES_SELECTION = '"h-index","mf-index"'; 
```

> Sorry, there is an uncaught Exception: There is no existing index with the name h-index.

any idea?

**Comment by arkuuu** [comment]
I think this is because of the other errors you described in https://github.com/arkuuu/publin/issues/22. 
There was an error scanning the path with the available indices, this would explain why he cannot find the h-index. 

I will look into this.

**Comment by arkuuu** [comment]
As alread mentioned in https://github.com/arkuuu/publin/issues/22, please make sure that your `ROOT_PATH` in the `config/Config.php` is set correctly. It may be misleading that the config template has `ROOT_PATH = '/'` set as default, but you need to set it to the full absolut path to your publin installation.

I will close this now, the issue should be resolved. Feel free to reopen it, if it still does not work for you.
